### PR TITLE
Docker-ise logchimp app

### PR DESCRIPTION
**Pull request by mittalyashu**
Create docker image of LogChimp application for easy deployments.

### CODE REVIEW

**Comment by mittalyashu** [comment]
> This comment is just to log the conversation from @bigint

Tried running `yarn docker:up` and got this error

`curl: (7) Failed to connect to localhost port 8080: Connection refused`

image

Running `docker ps -a`, postgresql docker container seems to be running fine but `frontend` and `backend` docker container stopped with error `Exited (127)`.

After checking the logs of both `frontend` and `backend` docker images, it seems that the packages are not getting installed when docker run a docker image.

image

**Comment by kaushikveluru** [comment]
Can you squash your commints on the PR?

**Comment by mittalyashu** [comment]
@kaushikveluru This PR is still work in progress. Once it's complete, I will squash the commits before merging.

**Comment by mittalyashu** [comment]
The development of the docker image has been move to separate repository https://github.com/logchimp/docker.

Instead of using docker-compose to manage multiple docker image (frontend, backend and database). A single docker image will be created.

**Pull request closed without merging**
